import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const load=lang=>JSON.parse(fs.readFileSync(new URL(`../data/${lang}/chapter.json`,import.meta.url)));
for(const lang of ['es','ja']){
 const c=load(lang);const L=c.language;const reading=c.reading==='romaji';
 test(`${lang}: every line carries target text, English, romaji where used, and valid vocabulary references`,()=>{const visit=v=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){if(typeof v[L]==='string'){assert.equal(typeof v.en,'string',v[L]);if(reading)assert.equal(typeof v.romaji,'string',v[L])}if(v.next){assert.equal(typeof v.nextEn,'string',v.next);if(reading)assert.equal(typeof v.nextRomaji,'string',v.next)}if(typeof v.correction==='string'){assert.equal(typeof v.correctionEn,'string');if(reading)assert.equal(typeof v.correctionRomaji,'string')}if(v.words)for(const id of v.words)assert.ok(c.items[id],id);if(v.illustrations)for(const id of v.illustrations)assert.ok(c.items[id],id);Object.values(v).forEach(visit)}};visit(c);assert.equal(L,lang)});
 test(`${lang}: quest ingredients can be taught, checked, handed over, delivered and reviewed with valid choices`,()=>{assert.equal(c.quest.items.length,3);for(const id of c.quest.items){assert.ok(c.items[id],id);assert.ok(c.teach[id]);assert.ok(c.received[id]);assert.ok(c.delivery[id]);assert.ok(c.review[id]);assert.equal(c.checks[id].correct,id);assert.ok(c.checks[id].options.includes(id));assert.equal(new Set(c.checks[id].options).size,c.checks[id].options.length);for(const choice of c.checks[id].options)assert.ok(c.items[choice])}for(const id of c.quest.reviewPool)assert.ok(c.items[id]&&c.review[id],id)});
 test(`${lang}: people, routes and engine lines are complete`,()=>{const hosts=Object.values(c.people).filter(p=>p.role==='host');assert.equal(hosts.length,1);for(const id of c.quest.items){const vendor=Object.entries(c.people).find(([,p])=>p.item===id);assert.ok(vendor,id);assert.equal(c.items[id].place,vendor[0])}for(const key of ['continue','correction','notYet','reviewIdle','reviewDone','tableEarly','hostReady','hostHint','cafeDoor','cafeGreeting','homeDoor','fountain'])assert.ok(c.lines[key],key);for(const key of ['cafeDoor','homeDoor'])assert.ok(c.lines[key].who&&c.lines[key].option,key);assert.equal(c.questSteps.length,4);for(const key of ['language','town','country','place','chapterEyebrow','talk','status','statusDone','statusIdle','questStart','chapterDone','added','homeTip','voiceOn','voiceOff','voiceNote','noteChallenge','noteSupport','noteFading','noteHelped','journalDone','canvasLabel'])assert.equal(typeof c.ui[key],'string',key);assert.equal(c.ui.routes.length,6);for(const [id]of c.ui.routes)assert.ok(c.people[id]||['cafe','table','home'].includes(id),id)});
}
test('the Japanese chapter is kana only, with hiragana as the default script and katakana reserved for loanwords',()=>{const c=load('ja');const visit=v=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){if(typeof v.ja==='string')assert.doesNotMatch(v.ja,/[一-鿿]/,`kanji in ${v.ja}`);Object.values(v).forEach(visit)}};visit(c);assert.equal(c.items.teeburu.ja,'テーブル');assert.match(c.items.gohan.ja,/^[ぁ-ゖ]+$/)});
