import {Town,AvatarPreview} from './world.js';
import {expose,answer,known,support,due,loadState,saveState,toKatakana} from './learning.js';
const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pictures={
 bread:'<ellipse cx="32" cy="23" rx="26" ry="12" transform="rotate(-17 32 23)" fill="#d9a65f"/><path d="M18 20l3 9m7-14l3 10m7-13l3 10" stroke="#f9e4b5" stroke-width="4" stroke-linecap="round"/>',
 tomato:'<circle cx="25" cy="26" r="14" fill="#c9674e"/><circle cx="44" cy="28" r="12" fill="#dc7956"/><path d="M23 10l-5 8 10-4-3 8 8-7M44 14l-4 8 10-4" stroke="#698551" fill="none" stroke-width="3"/>',
 oil:'<path d="M26 6h13v13l7 8v17H18V27l8-8z" fill="#7c9359"/><rect x="25" y="3" width="15" height="6" rx="2" fill="#a88451"/><rect x="21" y="28" width="22" height="12" rx="2" fill="#eee4bb"/><path d="M29 37l7-6" stroke="#7c9359" stroke-width="2"/>',
 water:'<path d="M17 10h30l-4 34H21z" fill="#9cbfb8"/><path d="M20 22h24l-2 19H22z" fill="#739e9b"/><path d="M23 14l2 21" stroke="#e1eddd" stroke-width="3"/>',
 apple:'<path d="M32 16c-25-18-30 28-8 29 6-2 7-2 13 0 22 0 21-44-5-29" fill="#96a367"/><path d="M31 18l3-13" stroke="#81684c" stroke-width="3"/><ellipse cx="41" cy="9" rx="8" ry="4" transform="rotate(-25 41 9)" fill="#6b864f"/>',
 cheese:'<path d="M10 30L44 9l12 21v14H10z" fill="#e0bf65"/><path d="M10 30h46L44 9z" fill="#efd58c"/><circle cx="24" cy="35" r="3" fill="#c5a34e"/><circle cx="43" cy="37" r="4" fill="#c5a34e"/>',
 table:'<path d="M9 19h46v8H9zM14 27h5v18h-5zm31 0h5v18h-5z" fill="#af8b59"/><path d="M7 16h50v7H7z" fill="#dac194"/>',
 sun:'<circle cx="32" cy="25" r="13" fill="#d9b778"/><path d="M32 3v5m0 35v5M9 25H3m52 0h6M15 8l4 4m26 26l4 4M15 42l4-4M45 12l4-4" stroke="#c5a469" stroke-width="3"/>',
 rice:'<path d="M9 24h46c0 13-9 21-23 21S9 37 9 24z" fill="#5d6f8c"/><path d="M11 24h42c0 3-1 5-2 7H13c-1-2-2-4-2-7z" fill="#8798b3"/><ellipse cx="32" cy="22" rx="21" ry="9" fill="#f7f3ea"/><path d="M20 20l3 3m8-6l2 4m9-2l2 3" stroke="#e2dccb" stroke-width="2.5" stroke-linecap="round"/>',
 salmon:'<path d="M8 25c10-13 30-16 46-8-4 10-12 16-24 18-9 1-16-3-22-10z" fill="#e9836c"/><path d="M14 24c9-8 22-11 36-7" stroke="#f6c5b3" stroke-width="3" fill="none"/><path d="M22 27c8-6 18-9 30-6" stroke="#f6c5b3" stroke-width="3" fill="none"/><path d="M52 17l8-7-2 12" fill="#d9705b"/>',
 tea:'<path d="M14 18h30v16c0 6-5 10-15 10S14 40 14 34z" fill="#eae3d1"/><path d="M17 21h24v12c0 4-4 7-12 7s-12-3-12-7z" fill="#8fa869"/><path d="M44 22h6c4 0 5 9 0 10h-6" stroke="#d9d0bb" stroke-width="4" fill="none"/><path d="M24 8c-2 4 2 5 0 9m8-9c-2 4 2 5 0 9" stroke="#c9c2b0" stroke-width="2.5" fill="none" stroke-linecap="round"/>',
 egg:'<path d="M32 5c11 0 18 14 18 25s-8 17-18 17-18-6-18-17S21 5 32 5z" fill="#f3e7cf"/><path d="M25 14c2-4 5-6 8-6" stroke="#fff9ee" stroke-width="3" stroke-linecap="round"/>'
};
function art(id){return `<svg viewBox="0 0 64 50" aria-hidden="true">${pictures[id]||pictures.sun}</svg>`}
const worlds={es:{file:'data/es/chapter.json',symbol:'☀'},ja:{file:'data/ja/chapter.json',symbol:'⛩'}};
let storage;try{storage=window.localStorage}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable')}}}
const chapters={};let lang,chapter,state,L,ui,town,preview,draft,editing=false,currentLine=null,assisted=false,voiceReady=false,timer,saveTimer=0,sessionStarted=false;
const fill=(s,vars)=>String(s).replace(/\{(\w+)\}/g,(m,k)=>vars[k]??m);
const items=()=>chapter.quest.items;
const collected=()=>items().every(id=>state.inventory.includes(id)||state.delivered.includes(id));
// Japanese text is authored in hiragana (katakana for loanwords); the reading toggle converts the whole line to katakana as a drill.
const kana=s=>chapter.reading&&state.script==='katakana'?toKatakana(s):s;
const word=s=>`<span lang="${lang}" data-raw="${escape(s)}">${escape(kana(s))}</span>`;
const romaji=s=>chapter.reading&&state.romaji&&s?`<small class="romaji">${escape(s)}</small>`:'';
function refreshScript(){document.querySelectorAll('[data-raw]').forEach(el=>el.textContent=kana(el.dataset.raw));$('script-toggle').textContent=state.script==='katakana'?'ア':'あ';$('script-toggle').setAttribute('aria-pressed',String(state.script==='katakana'));if(currentLine)$('target-line').textContent=kana(currentLine[L]);if(sessionStarted)updateHud()}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,3800)}
function persist(){const okay=saveState(storage,state);$('save-status').textContent=okay?`SAVED ON THIS DEVICE · ${ui.language.toUpperCase()}`:'SAVE UNAVAILABLE · KEEP THIS TAB OPEN';return okay}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function speak(text){if(!state.audio||!voiceReady||!('speechSynthesis'in window))return;stopVoice();const u=new SpeechSynthesisUtterance(text);u.lang=chapter.ttsLang;u.rate=.84;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===chapter.ttsLang)||voices.find(v=>v.lang.replace('_','-').startsWith(lang))||null;speechSynthesis.speak(u)}
function lock(value){town.blocked=value;town.keys.clear();town.path=[];$('interaction').hidden=value||!sessionStarted||!town.near}
function closeDialogue(){stopVoice();$('dialogue').hidden=true;currentLine=null;lock(false);persist();updateHud()}
function closeSheet(){$('sheet').hidden=true;lock(false)}
function showSheet(title,html){closeDialogue();$('sheet-title').textContent=title;$('sheet-content').innerHTML=html;$('sheet').hidden=false;lock(true);$('sheet-close').focus()}
function showLine(who,line,{challenge=false,options=[],onChoice,place}={}){
 $('sheet').hidden=true;lock(true);currentLine=line;assisted=false;expose(state.srs,line.words||[]);$('dialogue').hidden=false;const p=chapter.people[who];$('speaker').textContent=p?.name||line.who||who;$('speaker').lang=lang;$('dialogue-place').textContent=place||p?.place||ui.place;$('target-line').textContent=kana(line[L]);$('target-line').lang=lang;
 const helped=challenge?state.support==='full':support(state.srs,line.words||[],state.support);$('romaji-line').textContent=line.romaji||'';$('romaji-line').hidden=!(chapter.reading&&state.romaji&&line.romaji);
 $('english-line').textContent=line.en;$('english-line').hidden=!helped;assisted=challenge&&helped;$('translate').hidden=helped;$('feedback').textContent='';$('learning-note').textContent=challenge?ui.noteChallenge:helped?ui.noteSupport:ui.noteFading;
 $('choices').replaceChildren();if(line.illustrations){const examples=document.createElement('div');examples.className='illustrations';for(const id of line.illustrations){const item=chapter.items[id];const el=document.createElement('div');el.innerHTML=art(item.icon)+word(item[L])+romaji(item.romaji);examples.append(el)}$('choices').append(examples)}
 for(const option of options){const b=document.createElement('button');b.className='choice';b.innerHTML=(option.icon?art(option.icon):'')+word(option[L])+romaji(option.romaji)+(!challenge&&helped&&option.en?`<small>${escape(option.en)}</small>`:'');b.addEventListener('click',()=>{voiceReady=true;onChoice?.(option)});$('choices').append(b)}speak(line[L]);persist();$('close-dialogue').focus();
}
function script(who,lines,onEnd){let i=0;const next=()=>{const line=lines[i];const c=chapter.lines.continue;showLine(who,line,{options:[{[L]:line.next||c[L],romaji:line.nextRomaji||c.romaji,en:line.nextEn||c.en}],onChoice:()=>{i++;if(i<lines.length)next();else onEnd?.()}})};next()}
function check(who,id,line,context,onSuccess,options=null){
 const opts=options||chapter.checks[id]?.options||[id,...Object.keys(chapter.items).filter(k=>k!==id).slice(0,2)];const shuffled=[...opts].sort(()=>Math.random()-.5);let missed=false;
 showLine(who,line,{challenge:true,options:shuffled.map(k=>({id:k,[L]:chapter.items[k][L],romaji:chapter.items[k].romaji,icon:chapter.items[k].icon})),onChoice:opt=>{
 if(opt.id!==id){answer(state.srs,id,false,{context});assisted=true;missed=true;const c=chapter.checks[id]||{},f=chapter.lines.correction,item=chapter.items[id];const parts=[kana(c.correction||fill(f[L],{item:item[L]}))];if(chapter.reading&&state.romaji)parts.push(c.correctionRomaji||fill(f.romaji,{item:item.romaji}));parts.push(c.correctionEn||fill(f.en,{item:item.en}));$('feedback').textContent=parts.join(' · ');$('english-line').hidden=false;$('translate').hidden=true;persist();return}
 const result=answer(state.srs,id,true,{assisted:assisted||missed,context});if(result.credited)state.xp+=5;persist();onSuccess(result);
 }});
}
function updateHud(){
 const phase=state.quest==='new'?0:state.quest==='complete'?3:collected()?2:1;const step=chapter.questSteps[phase];$('hud-title').textContent=kana(chapter.title);$('quest-line').textContent=kana(step[L]);$('quest-line').lang=lang;$('quest-romaji').textContent=chapter.reading&&state.romaji?step.romaji||'':'';$('quest-english').textContent=step.en;const progress=phase===0?0:state.quest==='complete'?100:20+(state.inventory.length+state.delivered.length)*20;$('quest-progress').style.width=progress+'%';$('status').textContent=state.quest==='complete'?ui.statusDone:fill(ui.status,{name:state.character?.name||ui.traveller});
 town.dinnerFood.visible=state.quest==='complete';$('sound').textContent=state.audio?'♫':'♩';$('sound').setAttribute('aria-pressed',String(state.audio));
}
function pickup(who,id){
 if(state.quest==='new'){script(who,[chapter.lines.notYet],closeDialogue);return}
 if(state.inventory.includes(id)||state.delivered.includes(id)){review(who,id);return}
 script(who,[chapter.teach[id]],()=>check(who,id,chapter.checks[id],`collect-${who}`,()=>{if(!state.inventory.includes(id)){state.inventory.push(id);state.xp+=10}if(collected())state.quest='dinner';updateHud();persist();script(who,[chapter.received[id]],()=>{closeDialogue();notify(fill(ui.added,{item:kana(chapter.items[id][L])}))})}));
}
function review(who,fallback){const pool=items().filter(id=>state.inventory.includes(id)||state.delivered.includes(id));const queue=due(state.srs,pool);const id=queue.includes(fallback)?fallback:queue[0];if(!id){script(who,[chapter.lines.reviewIdle],closeDialogue);return}const reviewLine=chapter.review[id];check(who,id,reviewLine,`review-${who}`,()=>{script(who,[{...chapter.lines.reviewDone,words:[id]}],closeDialogue)},[id,...chapter.quest.reviewPool.filter(k=>k!==id).slice(0,2)])}
function host(){return Object.keys(chapter.people).find(id=>chapter.people[id].role==='host')}
function dinner(){
 const h=host();if(state.quest==='complete'){review(h,items()[0]);return}
 if(!collected()){script(h,[chapter.lines.tableEarly],closeDialogue);return}
 const remaining=items().filter(id=>!state.delivered.includes(id));const serve=()=>{if(!remaining.length){script(h,chapter.ending,()=>{state.quest='complete';state.xp+=30;closeDialogue();updateHud();persist();notify(ui.chapterDone)});return}const id=remaining[0];check(h,id,chapter.delivery[id],'dinner-table',()=>{state.delivered.push(id);state.inventory=state.inventory.filter(k=>k!==id);remaining.shift();persist();serve()},items())};serve();
}
function door(key,room,after){const line=chapter.lines[key];showLine(line.who,line,{options:[line.option],onChoice:()=>{closeDialogue();town.enter(room);state.position=town.position();persist();after?.()}})}
function interact(e){
 if(!sessionStarted||town.blocked)return;voiceReady=true;const person=chapter.people[e.id],lines=chapter.lines;
 if(person?.role==='host'){if(state.quest==='new')script(e.id,chapter.intro,()=>{state.quest='gather';state.xp+=10;closeDialogue();updateHud();persist();notify(ui.questStart)});else if(collected()&&state.quest!=='complete')script(e.id,[lines.hostReady],closeDialogue);else if(state.quest==='complete')review(e.id,items()[0]);else script(e.id,[lines.hostHint],closeDialogue);return}
 if(person?.item){pickup(e.id,person.item);return}
 const barista=Object.keys(chapter.people).find(id=>chapter.people[id].item&&chapter.items[chapter.people[id].item].place===id&&town.entities.some(t=>t.id===id&&t.room==='cafe'));
 switch(e.id){
 case'cafe':door('cafeDoor','cafe',()=>script(barista,[lines.cafeGreeting],()=>pickup(barista,chapter.people[barista].item)));break;
 case'home':door('homeDoor','home',()=>notify(ui.homeTip));break;
 case'exit':closeDialogue();town.enter('town');state.position=town.position();persist();break;
 case'mirror':openCreator(true);break;
 case'table':dinner();break;
 case'fountain':script(lines.fountain.who,[lines.fountain],closeDialogue);break;
 }}
function start(){sessionStarted=true;voiceReady=true;$('welcome').hidden=true;$('quest-hud').hidden=false;town.enabled=true;town.setAvatar(state.character);town.restore(state.position);updateHud();persist();$('world').focus();$('touch-controls').hidden=!matchMedia('(pointer:coarse)').matches;}
function openCreator(edit=false){editing=edit&&!!state.character;draft={name:'',skin:'#c98f68',hair:'#302b28',shirt:'#819273',style:'bob',body:'regular',eyes:'#443526',accessory:'none',...(state.character||{})};$('dialogue').hidden=true;stopVoice();$('sheet').hidden=true;lock(true);$('creator').hidden=false;$('character-name').value=draft.name;$('hair-style').value=draft.style;$('body-style').value=draft.body;$('eyes-style').value=draft.eyes;$('accessory').value=draft.accessory;$('creator-save').textContent=editing?'Save my look →':'Start my story →';renderSwatches();if(!preview)preview=new AvatarPreview($('avatar-preview'));preview.set(draft);$('character-name').focus()}
function renderSwatches(){for(const [root,key,colors,names]of [['skin-options','skin',['#f2c8a0','#dfaf80','#c98f68','#a56f4e','#805338','#573b30'],['Porcelain','Warm beige','Golden tan','Caramel','Deep brown','Rich brown']],['hair-options','hair',['#302b28','#6e4932','#aa7246','#c8ad72','#9d573c','#d9d3be'],['Black','Brown','Chestnut','Blonde','Auburn','Silver']],['shirt-options','shirt',['#819273','#bc8264','#809aaf','#c6b277','#8d7a97','#e0d6bd'],['Sage','Terracotta','Blue','Ochre','Lavender','Cream']]]){$(root).replaceChildren();colors.forEach((color,i)=>{const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=color;b.setAttribute('aria-label',`${key} ${names[i]}`);b.setAttribute('aria-pressed',String(draft[key]===color));b.addEventListener('click',()=>{draft[key]=color;renderSwatches();preview.set(draft)});$(root).append(b)})}}
function journal(){if(!sessionStarted){showSheet('Your story is waiting',`<p>Pick a world and create your character to begin. Spanish and Japanese each keep their own character, save and progress on this device.</p>`);return}const rows=Object.entries(state.srs).filter(([id])=>chapter.items[id]).map(([id,r])=>`<div class="journal-item"><div>${word(chapter.items[id][L])}${romaji(chapter.items[id].romaji)}<small>${escape(chapter.items[id].en)} · ${r.successes} spaced independent recalls</small></div><span class="pill">${known(state.srs,id)?'Familiar':r.successes?'Growing':'New'}</span></div>`).join('');const inv=state.inventory.map(id=>`<div>${art(chapter.items[id].icon)}${word(chapter.items[id][L])}</div>`).join('');const routes=ui.routes.map(([id,label])=>`<button class="secondary" data-go="${id}">${escape(label)}</button>`).join('');showSheet('Your little story',`<p><strong>${escape(state.character.name)}</strong> · ${state.xp} story XP · ${escape(ui.language)} beginner</p><h3 lang="${lang}">${escape(kana(chapter.title))}</h3>${chapter.titleRomaji?`<span class="romaji">${escape(chapter.titleRomaji)} · ${escape(chapter.titleEn)}</span>`:''}<p>${state.quest==='complete'?escape(ui.journalDone):escape(chapter.questSteps[state.quest==='new'?0:collected()?2:1].en)}</p><div class="inventory">${inv||'<p>Your basket is empty.</p>'}</div><div class="journal-routes">${routes}</div><h3>Words becoming yours</h3>${rows||'<p>Your first conversation starts your word collection.</p>'}<p class="muted">English fades for familiar phrases after at least three independent recalls, spaced apart and in different situations. Story XP does not remove support. Using a hint never costs you anything.</p>`);document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{closeSheet();if(town.room!=='town')town.enter('town');const e=town.entities.find(e=>e.id===b.dataset.go);if(e)town.walkTo(e.x,e.z,e)}))}
function help(){const reading=chapter.reading?`<h3>Reading Japanese</h3><p>Lines are written in kana with romaji underneath, so you can always sound them out. Loanwords such as テーブル keep their katakana. Switch the whole line to katakana with the <strong>あ / ア</strong> button in a conversation to practise reading both scripts.</p><label>Script<select id="script-mode"><option value="hiragana">Hiragana · with katakana loanwords</option><option value="katakana">Katakana · everything</option></select></label><label>Romaji<select id="romaji-mode"><option value="on">Always show romaji</option><option value="off">Hide romaji</option></select></label>`:'';showSheet('Make yourself at home',`<p>Walk with <strong>WASD or arrow keys</strong>, or click the ground. Drag to turn your camera, and scroll to zoom. Click a neighbour’s name to walk over, or press <strong>E</strong> when you’re nearby.</p><p>Open your journal with <strong>J</strong> for the quest, your basket, and directions. Visit the wardrobe at home—or the character button above—to edit your look. <strong>Escape</strong> closes a panel.</p><h3>Learn at your own pace</h3><p>Neighbours explain new words in English. Then you’ll choose real objects from their requests. Use “Show English help” whenever you need it. Mistakes get a gentle correction. Familiar phrases gradually need less translation.</p><label>English support<select id="support-mode"><option value="auto">Adaptive · fade with understanding</option><option value="full">Always show English</option></select></label>${reading}<p>${escape(ui.voiceNote)}</p><p>Your ${escape(ui.language)} character is saved in this browser. Each world keeps its own character and progress. The earlier 2D save is kept separately.</p>`);$('support-mode').value=state.support;$('support-mode').addEventListener('change',e=>{state.support=e.target.value;persist()});if(chapter.reading){$('script-mode').value=state.script;$('script-mode').addEventListener('change',e=>{state.script=e.target.value;persist();refreshScript()});$('romaji-mode').value=state.romaji?'on':'off';$('romaji-mode').addEventListener('change',e=>{state.romaji=e.target.value==='on';persist();if(sessionStarted)updateHud()})}}
function buildPicker(){const root=$('world-picker');root.replaceChildren();for(const code of Object.keys(worlds)){const u=chapters[code].ui;const b=document.createElement('button');b.type='button';b.className='world-card';b.dataset.world=code;b.setAttribute('role','radio');b.innerHTML=`<span class="world-symbol">${worlds[code].symbol}</span><span><strong>${escape(u.language)}</strong><small>${escape(u.town)} · ${escape(u.country)}</small><em></em></span>`;b.addEventListener('click',()=>selectWorld(code));root.append(b)}}
// Each world has its own chapter, save key, character and 3D town. Switching happens only on the welcome screen.
function selectWorld(code){lang=code;chapter=chapters[code];L=chapter.language;ui=chapter.ui;state=loadState(storage,code,chapter.quest.items);if(!('speechSynthesis'in window))state.audio=false;if(town.theme!==code)town.build(code);try{storage.setItem('linguaquest_world',code)}catch{}
 for(const b of document.querySelectorAll('.world-card')){const on=b.dataset.world===code;b.setAttribute('aria-checked',String(on));b.classList.toggle('selected',on);const s=loadState(storage,b.dataset.world,chapters[b.dataset.world].quest.items);b.querySelector('em').textContent=s.character?`Continue as ${s.character.name}`:'New story'}
 $('world-symbol').textContent=worlds[code].symbol;$('world-name').textContent=ui.town;$('world-sub').textContent=`${ui.country} · ${ui.tagline}`;$('hud-eyebrow').textContent=ui.chapterEyebrow;$('hud-title').textContent=kana(chapter.title);$('hud-title').lang=lang;$('sheet-eyebrow').textContent=ui.cornerEyebrow;$('creator-eyebrow').textContent=ui.creatorEyebrow;$('world').setAttribute('aria-label',ui.canvasLabel);$('welcome-note').textContent=`${worlds[code].symbol} ${ui.language} · Beginner friendly`;$('replay').setAttribute('aria-label',`Replay ${ui.language} audio`);$('script-toggle').hidden=!chapter.reading;$('script-toggle').textContent=state.script==='katakana'?'ア':'あ';
 $('continue').hidden=!state.character;$('begin').textContent=state.character?'Edit your character ↗':'Create your character ↗';$('save-status').textContent=`LOCAL SAVE · ${ui.language.toUpperCase()}`;$('status').textContent=ui.statusIdle;town.dinnerFood.visible=state.quest==='complete';$('sound').textContent=state.audio?'♫':'♩';
}
function leave(){closeDialogue();closeSheet();$('creator').hidden=true;town.enabled=false;sessionStarted=false;$('welcome').hidden=false;$('quest-hud').hidden=true;$('interaction').hidden=true;$('touch-controls').hidden=true;persist();selectWorld(lang)}
async function init(){try{await Promise.all(Object.entries(worlds).map(async([code,w])=>{const response=await fetch(w.file);if(!response.ok)throw Error(`The ${code} chapter could not be loaded`);chapters[code]=await response.json()}));let last=null;try{last=storage.getItem('linguaquest_world')}catch{}const first=worlds[last]?last:'es';
 town=new Town($('world'),{theme:first,onNear:e=>{$('interaction').hidden=!e||town.blocked||!sessionStarted;if(e)$('interact-label').textContent=e.type==='npc'?fill(ui.talk,{name:e.label}):e.label},onInteract:interact,onTravelFailed:()=>notify('That path is blocked. Try a nearby spot, or use WASD to walk around.'),onMove:pos=>{state.position=pos;if(Date.now()-saveTimer>5000){persist();saveTimer=Date.now()}}});buildPicker();selectWorld(first);$('loading').hidden=true;
 $('begin').onclick=()=>openCreator(!!state.character);$('continue').onclick=start;$('wardrobe').onclick=()=>openCreator(sessionStarted);$('creator-cancel').onclick=()=>{$('creator').hidden=true;lock(false);if(!sessionStarted)$('welcome').hidden=false};$('character-form').onsubmit=e=>{e.preventDefault();const name=$('character-name').value.trim();if(!name){$('character-name').focus();return}draft.name=name;state.character={...draft};$('creator').hidden=true;if(editing&&sessionStarted){town.setAvatar(state.character);lock(false);updateHud();persist();notify('Your new look is saved.')}else start()};
 for(const [id,key]of [['hair-style','style'],['body-style','body'],['eyes-style','eyes'],['accessory','accessory']])$(id).onchange=e=>{draft[key]=e.target.value;preview.set(draft)};
 $('journal').onclick=journal;$('help').onclick=help;$('sheet-close').onclick=closeSheet;$('close-dialogue').onclick=closeDialogue;$('interact').onclick=()=>town.near&&interact(town.near);$('translate').onclick=()=>{assisted=true;$('english-line').hidden=false;$('translate').hidden=true;$('learning-note').textContent=ui.noteHelped};$('replay').onclick=()=>{voiceReady=true;if(currentLine)speak(currentLine[L])};$('script-toggle').onclick=()=>{state.script=state.script==='katakana'?'hiragana':'katakana';persist();refreshScript()};$('sound').onclick=()=>{state.audio=!state.audio;voiceReady=true;if(!state.audio)stopVoice();persist();updateHud();notify(state.audio?ui.voiceOn:ui.voiceOff)};document.querySelector('.brand').onclick=e=>{e.preventDefault();if(sessionStarted)leave()};
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;if(e.key==='Escape'){if(!$('creator').hidden){$('creator').hidden=true;lock(false)}else if(!$('sheet').hidden)closeSheet();else if(!$('dialogue').hidden)closeDialogue()}if(e.key.toLowerCase()==='j'&&!e.repeat&&sessionStarted&&$('creator').hidden){if(!$('sheet').hidden)closeSheet();else journal()}});
 window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden){town.keys.clear();persist();stopVoice()}});
 // Trap focus inside an open dialog, leaving the 3D controls inactive behind it.
 window.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const panel=!$('creator').hidden?$('creator'):!$('sheet').hidden?$('sheet'):!$('dialogue').hidden?$('dialogue'):null;if(!panel)return;const controls=[...panel.querySelectorAll('button,input,select')].filter(el=>!el.disabled&&el.getClientRects().length);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
 }catch(e){$('loading').innerHTML='<div class="error-message"><h2>The town needs a moment.</h2><p>Your browser needs WebGL to explore the town. Try a current Chrome or Safari window with graphics acceleration enabled.</p><p>'+escape(e.message)+'</p><button class="primary" onclick="location.reload()">Try again</button></div>';console.error(e)}}
init();
