import {Town,AvatarPreview} from './world.js';
import {expose,answer,known,support,due,loadState,saveState} from './learning.js';
const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pictures={
 bread:'<ellipse cx="32" cy="23" rx="26" ry="12" transform="rotate(-17 32 23)" fill="#d9a65f"/><path d="M18 20l3 9m7-14l3 10m7-13l3 10" stroke="#f9e4b5" stroke-width="4" stroke-linecap="round"/>',
 tomato:'<circle cx="25" cy="26" r="14" fill="#c9674e"/><circle cx="44" cy="28" r="12" fill="#dc7956"/><path d="M23 10l-5 8 10-4-3 8 8-7M44 14l-4 8 10-4" stroke="#698551" fill="none" stroke-width="3"/>',
 oil:'<path d="M26 6h13v13l7 8v17H18V27l8-8z" fill="#7c9359"/><rect x="25" y="3" width="15" height="6" rx="2" fill="#a88451"/><rect x="21" y="28" width="22" height="12" rx="2" fill="#eee4bb"/><path d="M29 37l7-6" stroke="#7c9359" stroke-width="2"/>',
 water:'<path d="M17 10h30l-4 34H21z" fill="#9cbfb8"/><path d="M20 22h24l-2 19H22z" fill="#739e9b"/><path d="M23 14l2 21" stroke="#e1eddd" stroke-width="3"/>',
 apple:'<path d="M32 16c-25-18-30 28-8 29 6-2 7-2 13 0 22 0 21-44-5-29" fill="#96a367"/><path d="M31 18l3-13" stroke="#81684c" stroke-width="3"/><ellipse cx="41" cy="9" rx="8" ry="4" transform="rotate(-25 41 9)" fill="#6b864f"/>',
 cheese:'<path d="M10 30L44 9l12 21v14H10z" fill="#e0bf65"/><path d="M10 30h46L44 9z" fill="#efd58c"/><circle cx="24" cy="35" r="3" fill="#c5a34e"/><circle cx="43" cy="37" r="4" fill="#c5a34e"/>',
 table:'<path d="M9 19h46v8H9zM14 27h5v18h-5zm31 0h5v18h-5z" fill="#af8b59"/><path d="M7 16h50v7H7z" fill="#dac194"/>',
 sun:'<circle cx="32" cy="25" r="13" fill="#d9b778"/><path d="M32 3v5m0 35v5M9 25H3m52 0h6M15 8l4 4m26 26l4 4M15 42l4-4M45 12l4-4" stroke="#c5a469" stroke-width="3"/>'
};
function art(id){return `<svg viewBox="0 0 64 50" aria-hidden="true">${pictures[id]||pictures.sun}</svg>`}
let storage;try{storage=window.localStorage}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable')}}}
let state=loadState(storage),chapter,town,preview,draft,editing=false,currentLine=null,assisted=false,voiceReady=false,timer,saveTimer=0,sessionStarted=false;
const collected=()=>['pan','tomates','aceite'].every(id=>state.inventory.includes(id)||state.delivered.includes(id));
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,3800)}
function persist(){const okay=saveState(storage,state);$('save-status').textContent=okay?'SAVED ON THIS DEVICE · SPANISH':'SAVE UNAVAILABLE · KEEP THIS TAB OPEN';return okay}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function speak(text){if(!state.audio||!voiceReady||!('speechSynthesis'in window))return;stopVoice();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.rate=.84;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='es-ES')||voices.find(v=>v.lang.startsWith('es'))||null;speechSynthesis.speak(u)}
function lock(value){town.blocked=value;town.keys.clear();town.path=[];$('interaction').hidden=value||!sessionStarted||!town.near}
function closeDialogue(){stopVoice();$('dialogue').hidden=true;currentLine=null;lock(false);persist();updateHud()}
function closeSheet(){$('sheet').hidden=true;lock(false)}
function showSheet(title,html){closeDialogue();$('sheet-title').textContent=title;$('sheet-content').innerHTML=html;$('sheet').hidden=false;lock(true);$('sheet-close').focus()}
function showLine(who,line,{challenge=false,options=[],onChoice,place}={}){
 $('sheet').hidden=true;lock(true);currentLine=line;assisted=false;expose(state.srs,line.words||[]);$('dialogue').hidden=false;const p=chapter.people[who];$('speaker').textContent=p?.name||who;$('dialogue-place').textContent=place||p?.place||'VALDELUZ';$('spanish-line').textContent=line.es;$('spanish-line').lang='es';const show=challenge?state.support==='full':support(state.srs,line.words||[],state.support);$('english-line').textContent=line.en;$('english-line').hidden=!show;assisted=challenge&&show;$('translate').hidden=show;$('feedback').textContent='';$('learning-note').textContent=challenge?'Choose what you understand. English help is always here.':show?'English support · familiar words will need less help over time.':'You know these words. Your English support is fading.';
 $('choices').replaceChildren();if(line.illustrations){const examples=document.createElement('div');examples.className='illustrations';for(const id of line.illustrations){const item=chapter.items[id];const el=document.createElement('div');el.innerHTML=art(item.icon)+`<span lang="es">${escape(item.es)}</span>`;examples.append(el)}$('choices').append(examples)}
 for(const option of options){const b=document.createElement('button');b.className='choice';b.innerHTML=(option.icon?art(option.icon):'')+`<span lang="es">${escape(option.es)}</span>`+(!challenge&&show&&option.en?`<small>${escape(option.en)}</small>`:'');b.addEventListener('click',()=>{voiceReady=true;onChoice?.(option)});$('choices').append(b)}speak(line.es);persist();$('close-dialogue').focus();
}
function script(who,lines,onEnd){let i=0;const next=()=>{const line=lines[i];showLine(who,line,{options:[{es:line.next||'Continuar',en:line.nextEn||'Continue'}],onChoice:()=>{i++;if(i<lines.length)next();else onEnd?.()}})};next()}
function check(who,id,line,context,onSuccess,options=null){
 const opts=options||chapter.checks[id]?.options||[id,...Object.keys(chapter.items).filter(k=>k!==id).slice(0,2)];const shuffled=[...opts].sort(()=>Math.random()-.5);let missed=false;
 showLine(who,line,{challenge:true,options:shuffled.map(k=>({id:k,es:chapter.items[k].es,icon:chapter.items[k].icon})),onChoice:opt=>{
 if(opt.id!==id){answer(state.srs,id,false,{context});assisted=true;missed=true;$('feedback').textContent=(chapter.checks[id]?.correction||`Mira: ${chapter.items[id].es}. Prueba otra vez.`)+' '+(chapter.checks[id]?.correctionEn||`Look for ${chapter.items[id].en}. Try again.`);$('english-line').hidden=false;$('translate').hidden=true;persist();return}
 const result=answer(state.srs,id,true,{assisted:assisted||missed,context});if(result.credited)state.xp+=5;persist();onSuccess(result);
 }});
}
function updateHud(){
 const phase=state.quest==='new'?0:state.quest==='complete'?3:collected()?2:1;const step=chapter.questSteps[phase];$('quest-line').textContent=step.es;$('quest-english').textContent=step.en;const progress=phase===0?0:state.quest==='complete'?100:20+(state.inventory.length+state.delivered.length)*20;$('quest-progress').style.width=progress+'%';$('status').textContent=state.quest==='complete'?'Valdeluz feels a little more like home':`Hola, ${state.character?.name||'viajero'} · Take your time`;
 town.dinnerFood.visible=state.quest==='complete';$('sound').textContent=state.audio?'♫':'♩';$('sound').setAttribute('aria-pressed',String(state.audio));
}
function pickup(who,id){
 if(state.quest==='new'){script(who,[{es:'¡Hola! Lucía te espera en la plaza, junto a la fuente.',en:'Hello! Lucía is waiting for you in the square, beside the fountain.',words:['hola'],next:'Voy a verla.',nextEn:"I'll go and see her."}],closeDialogue);return}
 if(state.inventory.includes(id)||state.delivered.includes(id)){review(who,id);return}
 script(who,[chapter.teach[id]],()=>check(who,id,chapter.checks[id],`collect-${who}`,()=>{if(!state.inventory.includes(id)){state.inventory.push(id);state.xp+=10}if(collected())state.quest='dinner';updateHud();persist();script(who,[{es:`¡Muy bien! Aquí tienes ${chapter.items[id].es}. ¡Hasta luego!`,en:`Very good! ${id==='tomates'?'Here are':'Here is'} your ${chapter.items[id].en}. See you later!`,words:[id],illustrations:[id],next:'¡Gracias!',nextEn:'Thank you!'}],()=>{closeDialogue();notify(`${chapter.items[id].es} · added to your basket`)})}));
}
function review(who,fallback){const pool=['pan','tomates','aceite'].filter(id=>state.inventory.includes(id)||state.delivered.includes(id));const queue=due(state.srs,pool);const id=queue.includes(fallback)?fallback:queue[0];if(!id){script(who,[{es:'¡Qué gusto verte! Todo está tranquilo. Puedes dar un paseo y volver más tarde.',en:'Lovely to see you! All is quiet. You can take a walk and come back later.',words:[],next:'¡Hasta luego!',nextEn:'See you later!'}],closeDialogue);return}const reviewLine=chapter.review[id];check(who,id,reviewLine,`review-${who}`,()=>{script(who,[{es:'¡Eso es! Muchas gracias. Qué bien nos entendemos.',en:"That's it! Thank you. We're understanding each other well.",words:[id],next:'¡De nada!',nextEn:"You're welcome!"}],closeDialogue)},[id,...['pan','tomates','aceite','agua'].filter(k=>k!==id).slice(0,2)])}
function dinner(){
 if(state.quest==='complete'){review('lucia','pan');return}
 if(!collected()){script('Lucía',[{es:'Aquí está la mesa. Todavía necesitamos pan, tomates y aceite de oliva.',en:'Here is the table. We still need bread, tomatoes and olive oil.',words:['mesa','pan','tomates','aceite'],next:'Voy a buscarlos.',nextEn:"I'll go and get them."}],closeDialogue);return}
 const remaining=['pan','tomates','aceite'].filter(id=>!state.delivered.includes(id));const serve=()=>{if(!remaining.length){script('lucia',chapter.ending,()=>{state.quest='complete';state.xp+=30;closeDialogue();updateHud();persist();notify('Chapter complete · Welcome to the neighbourhood!')});return}const id=remaining[0];check('lucia',id,chapter.delivery[id],'dinner-table',()=>{state.delivered.push(id);state.inventory=state.inventory.filter(k=>k!==id);remaining.shift();persist();serve()},['pan','tomates','aceite'])};serve();
}
function interact(e){
 if(!sessionStarted||town.blocked)return;voiceReady=true;switch(e.id){
 case'lucia':if(state.quest==='new')script('lucia',chapter.intro,()=>{state.quest='gather';state.xp+=10;closeDialogue();updateHud();persist();notify('A new quest · Una mesa para todos')});else if(collected()&&state.quest!=='complete')script('lucia',[{es:'¡Tienes todo! Vamos a la mesa, al lado de la panadería.',en:'You have everything! Let’s go to the table next to the bakery.',words:['mesa'],next:'¡Vamos!',nextEn:"Let's go!"}],closeDialogue);else if(state.quest==='complete')review('lucia','pan');else script('lucia',[{es:'Mateo tiene pan, Inés tiene tomates y Diego tiene aceite de oliva en el café.',en:'Mateo has bread, Inés has tomatoes, and Diego has olive oil at the café.',words:['pan','tomates','aceite'],next:'¡Gracias, Lucía!',nextEn:'Thank you, Lucía!'}],closeDialogue);break;
 case'diego':pickup('cafe','aceite');break;case'mateo':pickup('mateo','pan');break;case'ines':pickup('ines','tomates');break;
 case'cafe':showLine('Café Azahar',{es:'La puerta está abierta. ¡Pasa!',en:'The door is open. Come in!',words:[]},{options:[{es:'Entrar al café',en:'Enter the café'}],onChoice:()=>{closeDialogue();town.enter('cafe');state.position=town.position();persist();script('cafe',[{es:'¡Hola! Te doy la bienvenida al café. Soy Diego.',en:"Hello! Welcome to the café. I'm Diego.",words:['hola'],next:'¡Hola, Diego!',nextEn:'Hello, Diego!'}],()=>pickup('cafe','aceite'))}});break;
 case'home':showLine('Mi casa',{es:'Tu casa en Valdeluz. Un lugar para empezar de nuevo.',en:'Your home in Valdeluz. A place for a fresh start.',words:[]},{options:[{es:'Entrar en casa',en:'Go inside'}],onChoice:()=>{closeDialogue();town.enter('home');state.position=town.position();persist();notify('Mi casa · Visit the wardrobe to change your look')}});break;
 case'exit':closeDialogue();town.enter('town');state.position=town.position();persist();break;
 case'mirror':if(town.room==='home')openCreator(true);else pickup('cafe','aceite');break;
 case'table':dinner();break;
 case'fountain':script('La fuente',[{es:'El agua de la fuente brilla al sol. Escucha… qué tranquilidad.',en:'The water in the fountain sparkles in the sun. Listen… how peaceful.',words:['agua'],illustrations:['agua'],next:'Me quedo un momento.',nextEn:"I'll stay a moment."}],closeDialogue);break;
 }}
function start(){sessionStarted=true;voiceReady=true;$('welcome').hidden=true;$('quest-hud').hidden=false;town.enabled=true;town.setAvatar(state.character);town.restore(state.position);updateHud();persist();$('world').focus();$('touch-controls').hidden=!matchMedia('(pointer:coarse)').matches;}
function openCreator(edit=false){editing=edit&&!!state.character;draft={name:'',skin:'#c98f68',hair:'#302b28',shirt:'#819273',style:'bob',body:'regular',eyes:'#443526',accessory:'none',...(state.character||{})};$('dialogue').hidden=true;stopVoice();$('sheet').hidden=true;lock(true);$('creator').hidden=false;$('character-name').value=draft.name;$('hair-style').value=draft.style;$('body-style').value=draft.body;$('eyes-style').value=draft.eyes;$('accessory').value=draft.accessory;$('creator-save').textContent=editing?'Save my look →':'Start my story →';renderSwatches();if(!preview)preview=new AvatarPreview($('avatar-preview'));preview.set(draft);$('character-name').focus()}
function renderSwatches(){for(const [root,key,colors,names]of [['skin-options','skin',['#f2c8a0','#dfaf80','#c98f68','#a56f4e','#805338','#573b30'],['Porcelain','Warm beige','Golden tan','Caramel','Deep brown','Rich brown']],['hair-options','hair',['#302b28','#6e4932','#aa7246','#c8ad72','#9d573c','#d9d3be'],['Black','Brown','Chestnut','Blonde','Auburn','Silver']],['shirt-options','shirt',['#819273','#bc8264','#809aaf','#c6b277','#8d7a97','#e0d6bd'],['Sage','Terracotta','Blue','Ochre','Lavender','Cream']]]){$(root).replaceChildren();colors.forEach((color,i)=>{const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=color;b.setAttribute('aria-label',`${key} ${names[i]}`);b.setAttribute('aria-pressed',String(draft[key]===color));b.addEventListener('click',()=>{draft[key]=color;renderSwatches();preview.set(draft)});$(root).append(b)})}}
function journal(){if(!sessionStarted){showSheet('Your story is waiting','<p>Create your character to begin your Spanish story. Your Japanese world will have its own character and progress in a future version.</p>');return}const rows=Object.entries(state.srs).filter(([id])=>chapter.items[id]).map(([id,r])=>`<div class="journal-item"><div><span lang="es">${escape(chapter.items[id].es)}</span><small>${escape(chapter.items[id].en)} · ${r.successes} spaced independent recalls</small></div><span class="pill">${known(state.srs,id)?'Familiar':r.successes?'Growing':'New'}</span></div>`).join('');const inv=state.inventory.map(id=>`<div>${art(chapter.items[id].icon)}<span lang="es">${escape(chapter.items[id].es)}</span></div>`).join('');showSheet('Your little story',`<p><strong>${escape(state.character.name)}</strong> · ${state.xp} story XP · Spanish beginner</p><h3 lang="es">${chapter.title}</h3><p>${state.quest==='complete'?'You helped prepare dinner. Visit your neighbours again: they will bring familiar words back when a review is due.':chapter.questSteps[state.quest==='new'?0:collected()?2:1].en}</p><div class="inventory">${inv||'<p>Your basket is empty.</p>'}</div><div class="journal-routes"><button class="secondary" data-go="lucia">Find Lucía</button><button class="secondary" data-go="mateo">Bakery</button><button class="secondary" data-go="ines">Market</button><button class="secondary" data-go="cafe">Café</button><button class="secondary" data-go="table">Dinner table</button><button class="secondary" data-go="home">Home</button></div><h3>Words becoming yours</h3>${rows||'<p>Your first conversation starts your word collection.</p>'}<p class="muted">English fades for familiar phrases after at least three independent recalls, spaced apart and in different situations. Story XP does not remove support. Using a hint never costs you anything.</p>`);document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{closeSheet();if(town.room!=='town')town.enter('town');const e=town.entities.find(e=>e.id===b.dataset.go);town.walkTo(e.x,e.z,e)}))}
function help(){showSheet('Make yourself at home',`<p>Walk with <strong>WASD or arrow keys</strong>, or click the ground. Drag to turn your camera, and scroll to zoom. Click a neighbour’s name to walk over, or press <strong>E</strong> when you’re nearby.</p><p>Open your journal with <strong>J</strong> for the quest, your basket, and directions. Visit the wardrobe at home—or the character button above—to edit your look. <strong>Escape</strong> closes a panel.</p><h3>Learn at your own pace</h3><p>Neighbours explain new words in English. Then you’ll choose real objects from their requests. Use “Show English help” whenever you need it. Mistakes get a gentle correction. Familiar phrases gradually need less translation.</p><label>English support<select id="support-mode"><option value="auto">Adaptive · fade with understanding</option><option value="full">Always show English</option></select></label><p>Voice uses your browser’s Spanish speech voice. It may sound different between devices. Reading works even when no voice is available.</p><p>Your Spanish character is saved in this browser. The earlier 2D save is kept separately. Japanese is planned as an independent world.</p>`);$('support-mode').value=state.support;$('support-mode').addEventListener('change',e=>{state.support=e.target.value;persist()})}
async function init(){try{const response=await fetch('data/es/chapter.json');if(!response.ok)throw Error('Spanish chapter could not be loaded');chapter=await response.json();town=new Town($('world'),{onNear:e=>{$('interaction').hidden=!e||town.blocked||!sessionStarted;if(e)$('interact-label').textContent=e.type==='npc'?`Hablar con ${e.label}`:e.label},onInteract:interact,onTravelFailed:()=>notify('That path is blocked. Try a nearby spot, or use WASD to walk around.'),onMove:pos=>{state.position=pos;if(Date.now()-saveTimer>5000){persist();saveTimer=Date.now()}}});$('loading').hidden=true;$('continue').hidden=!state.character;$('begin').textContent=state.character?'Edit your character ↗':'Create your character ↗';
 $('begin').onclick=()=>openCreator(!!state.character);$('continue').onclick=start;$('wardrobe').onclick=()=>openCreator(sessionStarted);$('creator-cancel').onclick=()=>{$('creator').hidden=true;lock(false);if(!sessionStarted)$('welcome').hidden=false};$('character-form').onsubmit=e=>{e.preventDefault();const name=$('character-name').value.trim();if(!name){$('character-name').focus();return}draft.name=name;state.character={...draft};$('creator').hidden=true;if(editing&&sessionStarted){town.setAvatar(state.character);lock(false);updateHud();persist();notify('Your new look is saved.')}else start()};
 for(const [id,key]of [['hair-style','style'],['body-style','body'],['eyes-style','eyes'],['accessory','accessory']])$(id).onchange=e=>{draft[key]=e.target.value;preview.set(draft)};
 $('journal').onclick=journal;$('help').onclick=help;$('sheet-close').onclick=closeSheet;$('close-dialogue').onclick=closeDialogue;$('interact').onclick=()=>town.near&&interact(town.near);$('translate').onclick=()=>{assisted=true;$('english-line').hidden=false;$('translate').hidden=true;$('learning-note').textContent='A little help is part of learning. Take your time.'};$('replay').onclick=()=>{voiceReady=true;if(currentLine)speak(currentLine.es)};$('sound').onclick=()=>{state.audio=!state.audio;voiceReady=true;if(!state.audio)stopVoice();persist();updateHud();notify(state.audio?'Spanish voice on':'Spanish voice off')};document.querySelector('.brand').onclick=e=>{e.preventDefault();if(!sessionStarted)return;closeDialogue();closeSheet();$('creator').hidden=true;town.enabled=false;sessionStarted=false;$('welcome').hidden=false;$('quest-hud').hidden=true;$('interaction').hidden=true;$('touch-controls').hidden=true;$('continue').hidden=false;persist()};
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;if(e.key==='Escape'){if(!$('creator').hidden){$('creator').hidden=true;lock(false)}else if(!$('sheet').hidden)closeSheet();else if(!$('dialogue').hidden)closeDialogue()}if(e.key.toLowerCase()==='j'&&!e.repeat&&sessionStarted&&$('creator').hidden){if(!$('sheet').hidden)closeSheet();else journal()}});
 window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden){town.keys.clear();persist();stopVoice()}});
 // Trap focus inside an open dialog, leaving the 3D controls inactive behind it.
 window.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const panel=!$('creator').hidden?$('creator'):!$('sheet').hidden?$('sheet'):!$('dialogue').hidden?$('dialogue'):null;if(!panel)return;const controls=[...panel.querySelectorAll('button,input,select')].filter(el=>!el.disabled&&el.getClientRects().length);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
 if(!('speechSynthesis'in window))state.audio=false;
 }catch(e){$('loading').innerHTML='<div class="error-message"><h2>The town needs a moment.</h2><p>Your browser needs WebGL to explore Valdeluz. Try a current Chrome or Safari window with graphics acceleration enabled.</p><p>'+escape(e.message)+'</p><button class="primary" onclick="location.reload()">Try again</button></div>';console.error(e)}}
init();
