// The shared third-person engine: renderer, camera, movement, path search, labels and interiors. World geometry comes from a themed builder.
import * as T from '../../vendor/three.module.js';
import {makeAvatar} from './parts.js';
import {valdeluz} from './valdeluz.js';
import {hinata} from './hinata.js';
export {AvatarPreview} from './preview.js';
const builders={es:valdeluz,ja:hinata};
export class Town{
 constructor(canvas,{theme='es',onNear,onInteract,onMove,onTravelFailed}={}){
 this.canvas=canvas;this.onNear=onNear;this.onInteract=onInteract;this.onMove=onMove;this.onTravelFailed=onTravelFailed;
 this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
 this.camera=new T.PerspectiveCamera(44,1,.1,180);this.keys=new Set();this.yaw=.22;this.pitch=.59;this.distance=15;this.enabled=false;this.blocked=false;this.time=0;this.target=new T.Vector3(0,1,5);this.focus=this.target.clone();this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.ground=new T.Plane(new T.Vector3(0,1,0),0);
 this.build(theme);this.bind();this.resize();this.last=performance.now();this.frame=requestAnimationFrame(t=>this.animate(t));
 }
 // Rebuild the whole scene for a world. Used when the player picks a different language on the welcome screen.
 build(theme){
 if(this.scene)this.scene.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose()});
 this.theme=theme;const w=builders[theme]||valdeluz;this.builder=w;this.scene=new T.Scene();this.scene.background=new T.Color(w.sky.background);this.scene.fog=new T.Fog(w.sky.background,...w.sky.fog);
 this.scene.add(new T.HemisphereLight(...w.sky.hemi));const light=new T.DirectionalLight(w.sky.sun[0],w.sky.sun[1]);light.position.set(...w.sky.sun[2]);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-38,right:38,top:35,bottom:-35,near:.5,far:90});light.shadow.normalBias=.045;this.scene.add(light);
 this.obstacles=[];this.cameraBlockers=[];this.entities=[];this.water=[];this.path=[];this.destination=null;this.near=null;this.returnPos=null;this.room='town';this.doors=w.doors;
 w.town(this);w.rooms(this);const c=this.player?.userData.config;this.player=makeAvatar(c);this.player.userData.config=c;this.player.position.set(0,0,10);this.player.rotation.y=Math.PI;this.scene.add(this.player);this.buildLabels();this.onNear?.(null);
 }
 obstacle(x,z,w,d){this.obstacles.push({x,z,w:w/2+.36,d:d/2+.36})}
 addEntity(id,label,x,z,type='npc',y=2.8){const e={id,label,x,z,type,y};this.entities.push(e);return e}
 npc(id,label,x,z,c,parent=this.scene){const avatar=makeAvatar(c);avatar.position.set(x,0,z);parent.add(avatar);const e=this.addEntity(id,label,x,z);e.avatar=avatar;return e}
 buildLabels(){const root=document.getElementById('labels');root.replaceChildren();for(const e of this.entities){const b=document.createElement('button');b.className='world-label';b.textContent=(e.type==='npc'?'✦ ':'')+e.label;b.setAttribute('aria-label',e.label);b.addEventListener('click',()=>{if(!this.enabled||this.blocked)return;this.walkTo(e.x,e.z,e)});root.append(b);e.labelEl=b}}
 setAvatar(c){const pos=this.player.position.clone(),rot=this.player.rotation.y;this.scene.remove(this.player);this.disposeAvatar(this.player);this.player=makeAvatar(c);this.player.userData.config=c;this.player.position.copy(pos);this.player.rotation.y=rot;this.scene.add(this.player)}
 disposeAvatar(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose()})}
 enter(room){this.room=room;this.homeRoom.visible=room==='home';this.cafeRoom.visible=room==='cafe';this.path=[];this.player.position.set(room==='town'?0:100,0,room==='town'?10:2);if(room!=='town'){this.returnPos=this.doors[room];if(this.roomSign)this.roomSign.visible=true}if(room==='town'&&this.returnPos)this.player.position.set(this.returnPos.x,0,this.returnPos.z);this.yaw=0;this.distance=room==='town'?15:10;this.focus.copy(this.player.position);this.focus.y=1;this.onMove?.(this.position())}
 position(){return{x:this.player.position.x,z:this.player.position.z,room:this.room}}
 restore(pos){if(!pos)return;if(pos.room&&pos.room!=='town'){this.enter(pos.room);return}if(Number.isFinite(pos.x)&&Number.isFinite(pos.z)&&!this.collides(pos.x,pos.z))this.player.position.set(pos.x,0,pos.z)}
 collides(x,z){if(this.room!=='town')return x<94.5||x>105.5||z<-4.5||z>4.5;return Math.abs(x)>29||z<-20||z>26||this.obstacles.some(o=>Math.abs(x-o.x)<o.w&&Math.abs(z-o.z)<o.d)}
 walkTo(x,z,entity=null){const start={x:Math.round(this.player.position.x),z:Math.round(this.player.position.z)},goal={x:Math.round(x),z:Math.round(z)};const open=[{...start,g:0,f:0}],seen=new Map(),closed=new Set(),key=n=>`${n.x},${n.z}`;let end=null;seen.set(key(start),open[0]);for(let count=0;open.length&&count<4500;count++){open.sort((a,b)=>a.f-b.f);const n=open.shift();if(closed.has(key(n)))continue;closed.add(key(n));if(Math.hypot(n.x-goal.x,n.z-goal.z)<(entity?1.7:.8)){end=n;break}for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const next={x:n.x+dx,z:n.z+dz};if(this.collides(next.x,next.z)||this.collides(n.x+dx,n.z)||this.collides(n.x,n.z+dz)||closed.has(key(next)))continue;const g=n.g+Math.hypot(dx,dz),old=seen.get(key(next));if(old&&old.g<=g)continue;Object.assign(next,{g,f:g+Math.hypot(next.x-goal.x,next.z-goal.z),parent:n});seen.set(key(next),next);open.push(next)}}this.path=[];if(end){while(end.parent){this.path.unshift({x:end.x,z:end.z});end=end.parent}this.destination=entity;if(!this.path.length&&entity)this.onInteract?.(entity)}else {this.destination=null;this.onTravelFailed?.()}}
 bind(){this.resizeFn=()=>this.resize();window.addEventListener('resize',this.resizeFn);window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e'].includes(e.key.toLowerCase())){if(this.enabled&&!this.blocked)e.preventDefault();this.keys.add(e.key.toLowerCase())}if(e.key.toLowerCase()==='e'&&!e.repeat&&this.enabled&&!this.blocked&&this.near)this.onInteract?.(this.near)});window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{this.keys.clear();this.drag=null});
 this.canvas.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!this.drag||this.blocked)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY)>5)this.drag.moved=true;if(this.drag.moved){this.yaw-=dx*.006;this.pitch=T.MathUtils.clamp(this.pitch+dy*.004,.25,1.05)}this.drag.x=e.clientX;this.drag.y=e.clientY});this.canvas.addEventListener('pointerup',e=>{if(this.drag&&!this.drag.moved&&this.enabled&&!this.blocked){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const p=new T.Vector3();if(this.ray.ray.intersectPlane(this.ground,p)&&!this.collides(p.x,p.z))this.walkTo(p.x,p.z)}this.drag=null});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.distance=T.MathUtils.clamp(this.distance+e.deltaY*.012,6,24)},{passive:false});this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
 document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.keys.add(b.dataset.move)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>this.keys.delete(b.dataset.move))});
 }
 resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix()}
 animate(now){const dt=Math.min((now-this.last)/1000,.04);this.last=now;this.time+=dt;let moving=false;const p=this.player.position;
 if(this.enabled&&!this.blocked){let dx=0,dz=0;if(this.keys.has('w')||this.keys.has('arrowup'))dz--;if(this.keys.has('s')||this.keys.has('arrowdown'))dz++;if(this.keys.has('a')||this.keys.has('arrowleft'))dx--;if(this.keys.has('d')||this.keys.has('arrowright'))dx++;if(dx||dz){this.path=[];this.destination=null;const a=dx*Math.cos(this.yaw)+dz*Math.sin(this.yaw),b=-dx*Math.sin(this.yaw)+dz*Math.cos(this.yaw);dx=a;dz=b}else if(this.path.length){dx=this.path[0].x-p.x;dz=this.path[0].z-p.z;if(Math.hypot(dx,dz)<.16){this.path.shift();if(!this.path.length&&this.destination){const e=this.destination;this.destination=null;this.onInteract?.(e)}dx=dz=0}}
 if(dx||dz){const len=Math.hypot(dx,dz),step=4.4*dt;dx=dx/len*step;dz=dz/len*step;if(!this.collides(p.x+dx,p.z))p.x+=dx;if(!this.collides(p.x,p.z+dz))p.z+=dz;this.player.rotation.y=Math.atan2(dx,dz);moving=true;this.onMove?.(this.position())}}
 for(let i=0;i<2;i++){this.player.userData.legs[i].rotation.x=moving?Math.sin(this.time*12+i*Math.PI)*.55:0;this.player.userData.arms[i].rotation.x=moving?Math.sin(this.time*12+(1-i)*Math.PI)*.4:Math.sin(this.time*1.5)*.02}
 for(const e of this.entities){if(e.avatar){e.avatar.position.y=Math.sin(this.time*1.6+e.x)*.018;if(Math.hypot(p.x-e.x,p.z-e.z)<4)e.avatar.rotation.y=Math.atan2(p.x-e.x,p.z-e.z)}}
 for(let i=0;i<this.water.length;i++){const w=this.water[i];w.mesh.position.y=w.top-((this.time*.7+i*.13)%1)*w.fall}
 this.builder.tick?.(this,dt);
 const aim=this.enabled?new T.Vector3(p.x,1.1,p.z):new T.Vector3(0,1,0);this.focus.lerp(aim,1-Math.exp(-dt*5));const dist=this.enabled?this.distance:36;const yaw=this.enabled?this.yaw:.27;const pitch=this.enabled?this.pitch:.65;const offset=new T.Vector3(Math.sin(yaw)*Math.cos(pitch)*dist,Math.sin(pitch)*dist,Math.cos(yaw)*Math.cos(pitch)*dist);if(this.enabled&&this.room==='town'){this.ray.set(this.focus,offset.clone().normalize());this.ray.far=offset.length();const hits=this.ray.intersectObjects(this.cameraBlockers,false);if(hits.length)offset.setLength(Math.max(2.5,hits[0].distance-.5));this.ray.far=Infinity}this.camera.position.copy(this.focus).add(offset);this.camera.lookAt(this.focus);
 let near=null,nd=2.5;for(const e of this.entities){const same=((this.room==='town')===(e.x<80))&&(!e.room||e.room===this.room);const d=Math.hypot(p.x-e.x,p.z-e.z);if(same&&d<nd){near=e;nd=d}const v=new T.Vector3(e.x,e.y,e.z).project(this.camera);const visible=this.enabled&&!this.blocked&&same&&v.z<1&&Math.abs(v.x)<.96&&Math.abs(v.y)<.9&&d<20;e.labelEl.hidden=!visible;if(visible){e.labelEl.style.left=`${(v.x*.5+.5)*innerWidth}px`;e.labelEl.style.top=`${(-v.y*.5+.5)*innerHeight}px`}}
 if(near!==this.near){this.near=near;this.onNear?.(near)}this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(t=>this.animate(t));
 }
}
